# Generated by Django 4.2.4 on 2023-10-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDRReader', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
