version: "0.9"
services:
  database:
    #container_name: dbservice
    image: mariadb:latest
    restart: on-failure # always
    env_file:
      ./db-env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/maria-init.sql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      
  # frontend:
  #   platform: linux/arm64
  #   build:
  #     context: .
  #     dockerfile: ./FinancierFrontend/Dockerfile
  #   restart: on-failure
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     default:
  #       aliases:
  #         - financierfrontend
  #         - financiar-frontend
    # volumes:
    #   - frontend_data:/FinancierFrontend

  backend:
    build:
      context: .
      dockerfile: ./FinancierBackend/Dockerfile
    depends_on:
      - database
      - redis
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - financierbackend
          - financiar-backend
    volumes:
      - ./FinancierBackend/FinancierBackend:/FinancierBackend

# volumes:
#   frontend_data: