version: "0.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./FinancierFrontend/Dockerfile
    restart: on-failure
    ports:
      - "5173:5173"
    networks:
      default:
        aliases:
          - financierfrontend
          - financiar-frontend
    volumes:
      - ./FinancierFrontend/FinancierFrontend:/FinancierFrontend

  backend:
    build:
      context: .
      dockerfile: ./FinancierBackend/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - financierbackend
          - financiar-backend
    volumes:
      - ./FinancierBackend/FinancierBackend:/FinancierBackend

  database:
    #container_name: dbservice
    image: mariadb:latest
    restart: on-failure # always
    env_file:
      ./db-env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/maria-init.sql
    ports:
      - "3306:3306"
