# Generated by Django 4.2.4 on 2023-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDRReader', '0003_stock_desc_stock_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='link',
            field=models.TextField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='recent',
            field=models.FloatField(default=0.0),
        ),
    ]
