# Generated by Django 4.2.4 on 2023-10-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FDRReader', '0003_stock_desc_stock_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=200)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FDRReader.stock')),
            ],
        ),
    ]
